# JVM：给 Gradle 自己用的。国内首次构建要下 AGP 与其传递依赖，2G 够用。
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# 并行 + 构建缓存，二次构建快很多
org.gradle.parallel=true
org.gradle.caching=true

# 我们是单模块小工程，关掉配置缓存能少一类玄学报错
org.gradle.configuration-cache=false

# 没有用任何 androidx 组件（纯 android.* 原生 API），
# 这两个开关只是为了绕过 AGP 8 的默认校验。
android.useAndroidX=true
android.enableJetifier=false

android.nonTransitiveRClass=true
android.defaults.buildfeatures.buildconfig=false
